import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import Decenza

// Value picker opened from the grindQuickSelect layout widget. Lists the grind
// settings the widget generated (current +/- 5 steps, or an observed-history
// fallback) and applies the tapped value. This is a plain VALUE picker — not a
// preset editor — so it is far simpler than RatioPresetDialog.
//
// Pure UI: no AI dependencies. The list (`rows`) is computed by the
// item; the finer/coarser end is annotated when meaningful (numeric or letter
// mode). Rows are ordered fine -> coarse as generated by the item (smallest
// value / earliest letter first), matching the Finer (top) / Coarser (bottom)
// end labels.
Dialog {
    id: root
    parent: Overlay.overlay
    anchors.centerIn: parent
    width: Math.min(Theme.scaled(360), parent ? parent.width * 0.95 : Theme.scaled(360))
    height: Math.min(contentCol.implicitHeight + Theme.scaled(40), parent ? parent.height * 0.92 : Theme.scaled(640))
    modal: true
    closePolicy: Dialog.CloseOnEscape | Dialog.CloseOnPressOutside
    padding: 0

    // [{ value: string, isCurrent: bool }] — fine -> coarse order.
    property var rows: []
    // Whether to show the finer/coarser end annotations (numeric/letter modes).
    property bool finerHint: false

    signal valuePicked(string value)

    background: Rectangle {
        color: Theme.surfaceColor
        radius: Theme.cardRadius
        border.width: 1
        border.color: Theme.borderColor
    }

    contentItem: Flickable {
        contentWidth: width
        contentHeight: contentCol.implicitHeight
        clip: true
        boundsBehavior: Flickable.StopAtBounds
        ScrollBar.vertical: ScrollBar { policy: ScrollBar.AsNeeded }

        ColumnLayout {
            id: contentCol
            width: parent.width
            spacing: Theme.spacingSmall

            // --- Header ---
            ColumnLayout {
                Layout.fillWidth: true
                Layout.topMargin: Theme.spacingLarge
                Layout.leftMargin: Theme.spacingLarge
                Layout.rightMargin: Theme.spacingLarge
                spacing: Theme.scaled(2)
                Text {
                    text: TranslationManager.translate("grind.picker.title", "Grind Setting")
                    color: Theme.textColor
                    font.pixelSize: Theme.scaled(24); font.bold: true
                }
                Text {
                    text: TranslationManager.translate("grind.picker.subtitle", "Tap a value to set the grinder")
                    color: Theme.textSecondaryColor
                    font: Theme.labelFont
                }
            }

            // --- Finer end label (top: rows ascend, so smallest number /
            //     earliest letter = finest is first). ---
            Text {
                visible: root.finerHint && root.rows.length > 2
                Layout.fillWidth: true
                Layout.leftMargin: Theme.spacingLarge
                Layout.rightMargin: Theme.spacingLarge
                horizontalAlignment: Text.AlignHCenter
                text: TranslationManager.translate("grind.picker.finer", "Finer").toUpperCase()
                color: Theme.textSecondaryColor
                font: Theme.captionFont
            }

            // --- Value rows ---
            Repeater {
                model: root.rows
                delegate: Rectangle {
                    id: rowRect
                    required property var modelData
                    readonly property bool isCurrent: modelData.isCurrent === true
                    Layout.fillWidth: true
                    Layout.leftMargin: Theme.spacingLarge
                    Layout.rightMargin: Theme.spacingLarge
                    Layout.preferredHeight: Theme.scaled(48)
                    radius: Theme.buttonRadius
                    color: rowMa.pressed ? Qt.darker(Theme.backgroundColor, 1.1) : Theme.backgroundColor
                    border.width: isCurrent ? 2 : 1
                    border.color: isCurrent ? Theme.primaryColor : Theme.borderColor

                    Accessible.role: Accessible.Button
                    Accessible.name: String(modelData.value)
                                     + (isCurrent ? ", " + TranslationManager.translate("grind.picker.current", "current") : "")
                    Accessible.focusable: true
                    Accessible.onPressAction: rowMa.clicked(null)

                    RowLayout {
                        anchors.fill: parent
                        anchors.leftMargin: Theme.spacingMedium
                        anchors.rightMargin: Theme.spacingMedium
                        spacing: Theme.spacingSmall
                        Text {
                            text: String(rowRect.modelData.value)
                            color: rowRect.isCurrent ? Theme.primaryColor : Theme.textColor
                            font.pixelSize: Theme.scaled(20)
                            font.bold: rowRect.isCurrent
                        }
                        Item { Layout.fillWidth: true }
                        Text {
                            visible: rowRect.isCurrent
                            text: TranslationManager.translate("grind.picker.current", "current").toUpperCase()
                            color: Theme.primaryColor
                            font: Theme.captionFont
                        }
                    }

                    MouseArea {
                        id: rowMa
                        anchors.fill: parent
                        onClicked: {
                            root.valuePicked(String(rowRect.modelData.value))
                            root.close()
                        }
                    }
                }
            }

            // --- Empty state: no value could be generated (burr grinder with an
            //     unset setting AND no shot history for it). Explain the dead-end
            //     instead of showing a title + Close with nothing between, and
            //     point the user at where to establish a first value. ---
            Text {
                visible: root.rows.length === 0
                Layout.fillWidth: true
                Layout.leftMargin: Theme.spacingLarge
                Layout.rightMargin: Theme.spacingLarge
                Layout.topMargin: Theme.spacingSmall
                horizontalAlignment: Text.AlignHCenter
                wrapMode: Text.WordWrap
                text: TranslationManager.translate("grind.picker.empty",
                    "Set a grind value in Brew Settings first, then this list fills in around it.")
                color: Theme.textSecondaryColor
                font: Theme.bodyFont
            }

            // --- Coarser end label (bottom: largest number / latest letter). ---
            Text {
                visible: root.finerHint && root.rows.length > 2
                Layout.fillWidth: true
                Layout.leftMargin: Theme.spacingLarge
                Layout.rightMargin: Theme.spacingLarge
                horizontalAlignment: Text.AlignHCenter
                text: TranslationManager.translate("grind.picker.coarser", "Coarser").toUpperCase()
                color: Theme.textSecondaryColor
                font: Theme.captionFont
            }

            // --- Close ---
            Rectangle {
                Layout.fillWidth: true
                Layout.leftMargin: Theme.spacingLarge
                Layout.rightMargin: Theme.spacingLarge
                Layout.topMargin: Theme.spacingSmall
                Layout.bottomMargin: Theme.spacingLarge
                Layout.preferredHeight: Theme.scaled(48)
                radius: Theme.buttonRadius
                color: closeMa.pressed ? Qt.darker(Theme.primaryColor, 1.15) : Theme.primaryColor
                Accessible.role: Accessible.Button
                Accessible.name: TranslationManager.translate("common.button.close", "Close")
                Accessible.focusable: true
                Accessible.onPressAction: closeMa.clicked(null)
                Text {
                    anchors.centerIn: parent
                    text: TranslationManager.translate("common.button.close", "Close")
                    color: Theme.primaryContrastColor
                    font: Theme.bodyFont
                }
                MouseArea { id: closeMa; anchors.fill: parent; onClicked: root.close() }
            }
        }
    }
}
